import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import http from 'node:http';
import {DatabaseSync} from 'node:sqlite';
import {briefSchema} from '../lib/creative-policy.mjs';

const png='iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aizsAAAAASUVORK5CYII=';
test('beta privado: instalação, convites, isolamento, arte protegida e idempotência',async()=>{
 const dir=fs.mkdtempSync(path.join(os.tmpdir(),'vt-ai-http-'));
 const previous={dir:process.env.VT_AI_DATA_DIR,key:process.env.OPENAI_API_KEY,setup:process.env.VT_AI_SETUP_CODE,origin:process.env.VT_AI_PUBLIC_ORIGIN},nativeFetch=globalThis.fetch;
 process.env.VT_AI_DATA_DIR=dir;process.env.OPENAI_API_KEY='mock-key-for-isolated-test';process.env.VT_AI_SETUP_CODE='setup-code-for-isolated-testing-123456';delete process.env.VT_AI_PUBLIC_ORIGIN;
 const plan={...Object.fromEntries(Object.entries(briefSchema.properties).filter(([,item])=>item.type==='string').map(([name])=>[name,''])),headline:'Feliz Dia do Cliente',copy_origin:{headline:'tematica',support:'vazio',cta:'vazio'},facts:[],alerts:[]};
 let paidCalls=0;
 globalThis.fetch=async url=>{paidCalls++;return url.endsWith('/responses')?Response.json({output:[{content:[{type:'output_text',text:JSON.stringify(plan)}]}]}):Response.json({data:[{b64_json:png}]})};
 let closeStudio,server;
 try{
  ({server,closeStudio}=await import('../server.mjs'));globalThis.fetch=nativeFetch;
  await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
  const address=`http://127.0.0.1:${server.address().port}`;
  const request=(route,{method='GET',body,cookie,headers={}}={})=>nativeFetch(address+route,{method,headers:{...(body!==undefined?{'Content-Type':'application/json'}:{}),...(cookie?{Cookie:cookie}:{}),...headers},body:body!==undefined?JSON.stringify(body):undefined});
  const post=(route,body,cookie)=>request(route,{method:'POST',body,cookie});
  const health=await (await request('/api/health')).json();assert.equal(health.version,'1.2.0');assert.equal(health.dataDir,dir);
  assert.equal((await request('/api/clients')).status,401);
  assert.equal((await request('/api/knowledge?q=Pedido%20curto')).status,401);
  assert.equal((await request('/files/anything.png')).status,401);
  assert.equal((await request('/')).status,200);
  assert.match(await (await request('/creative.js')).text(),/Gerar minha arte/);
  assert.match(await (await request('/')).text(),/studio\.css/);
  assert.match(await (await request('/studio.css')).text(),/auth-shell/);
  assert.deepEqual(await (await request('/api/auth/status')).json(),{setup_required:true,setup_configured:true});
  assert.equal((await post('/api/auth/setup',{email:'owner@example.com',name:'Dona VT',password:'very-long-password',setup_code:'wrong'})).status,403);
  const setup=await post('/api/auth/setup',{email:'owner@example.com',name:'Dona VT',password:'very-long-password',setup_code:process.env.VT_AI_SETUP_CODE});
  assert.equal(setup.status,200);const ownerCookie=setup.headers.get('set-cookie').split(';')[0];assert.match(setup.headers.get('set-cookie'),/HttpOnly/);assert.match(setup.headers.get('set-cookie'),/SameSite=Lax/);
  assert.equal((await setup.json()).user.role,'admin');
  const stored=new DatabaseSync(path.join(dir,'studio.sqlite'));
  assert.ok(!stored.prepare('SELECT password_hash FROM users WHERE email=?').get('owner@example.com').password_hash.includes('very-long-password'));
  assert.ok(!stored.prepare('SELECT token_hash FROM sessions LIMIT 1').get().token_hash.includes(ownerCookie.split('=')[1]));
  stored.close();
  assert.equal((await post('/api/auth/setup',{email:'bad@example.com',name:'Outro',password:'very-long-password',setup_code:process.env.VT_AI_SETUP_CODE})).status,409);
  const knowledge=await (await request('/api/knowledge?q=Pedido%20curto',{cookie:ownerCookie})).json();assert.ok(knowledge.some(item=>item.source==='conhecimento/14_intuicao_e_producao.md'));
  const ownerClients=await (await request('/api/clients',{cookie:ownerCookie})).json();assert.equal(ownerClients.length,1);assert.match(ownerClients[0].name,/Café Aurora/);
  const invited=await post('/api/auth/invites',{},ownerCookie);const invite=(await invited.json()).code;assert.equal(invite.length,43);
  assert.equal((await post('/api/auth/register',{email:'friend@example.com',name:'Amigo',password:'another-long-password',invite_code:'fake'})).status,403);
  const registered=await post('/api/auth/register',{email:'friend@example.com',name:'Amigo',password:'another-long-password',invite_code:invite});
  assert.equal(registered.status,200);const friendCookie=registered.headers.get('set-cookie').split(';')[0];assert.equal((await registered.json()).user.role,'tester');
  assert.equal((await post('/api/auth/register',{email:'second@example.com',name:'Outra',password:'another-long-password',invite_code:invite})).status,403);
  assert.equal((await post('/api/auth/invites',{},friendCookie)).status,403);
  assert.equal((await post('/api/backup',{},friendCookie)).status,403);
  assert.deepEqual(await (await request('/api/clients',{cookie:friendCookie})).json(),[]);
  assert.equal((await request('/api/projects',{cookie:friendCookie}).then(r=>r.json())).length,0);
  assert.equal((await request('/api/pieces',{cookie:friendCookie}).then(r=>r.json())).length,0);
  assert.equal((await request('/api/generations',{cookie:friendCookie}).then(r=>r.json())).length,0);
  assert.equal((await request('/api/clients',{method:'PATCH',body:{id:ownerClients[0].id,name:'Roubado'},cookie:friendCookie})).status,400);
  assert.equal((await post('/api/projects',{client_id:ownerClients[0].id,name:'Indevida'},friendCookie)).status,400);
  const client=await (await post('/api/clients',{name:'Marca do amigo',niche:'Varejo'},friendCookie)).json();
  assert.equal((await request('/api/clients',{cookie:ownerCookie}).then(r=>r.json())).length,1);
  assert.equal((await post('/api/briefing',{prompt:'Dia do Cliente para a marca.',client_id:client.id,images:[]},ownerCookie)).status,404);
  const input={prompt:'Dia do Cliente para uma cafeteria.',images:[],request_id:'repeated-request-123'};
  const first=await (await post('/api/briefing',input,friendCookie)).json(),second=await (await post('/api/briefing',input,friendCookie)).json();assert.equal(first._token,second._token);assert.equal(paidCalls,1);
  assert.equal((await post('/api/briefing',{...input,prompt:'Outro pedido totalmente diferente.'},friendCookie)).status,400);assert.equal(paidCalls,1);
  await post('/api/briefing',input,ownerCookie);assert.equal(paidCalls,2);
  const generated=await post('/api/generate',{prompt:input.prompt,images:[]},friendCookie);assert.equal(generated.status,200);const art=await generated.json();assert.ok(art.id);assert.match(art.url,/^\/files\//);
  assert.equal((await request(art.url,{cookie:friendCookie})).status,200);
  assert.equal((await request(art.url,{cookie:ownerCookie})).status,404);
  assert.equal((await request(art.url)).status,401);
  assert.equal((await post('/api/generate/adapt',{generation_id:art.id,target_format:'story'},ownerCookie)).status,404);
  assert.equal((await post('/api/generate/feedback',{generation_id:art.id,verdict:'aprovada'},ownerCookie)).status,404);
  assert.equal((await request('/api/generations',{cookie:ownerCookie}).then(r=>r.json())).length,0);
  const cross=await request('/api/briefing',{method:'POST',body:input,cookie:friendCookie,headers:{Origin:'https://external.test'}});assert.equal(cross.status,403);
  const hostStatus=await new Promise(resolve=>{const req=http.get(address+'/api/health',{headers:{Host:'evil.test'}},response=>{response.resume();resolve(response.statusCode)});req.on('error',()=>resolve(0))});assert.equal(hostStatus,403);
  assert.equal((await request('/files/..%2Fstudio.sqlite',{cookie:friendCookie})).status,404);
  assert.equal((await request('/api/generate',{method:'POST',body:'{',cookie:friendCookie})).status,400);
  assert.ok(!JSON.stringify(first).includes('mock-key-for-isolated-test'));
  await post('/api/auth/logout',{},friendCookie);
  assert.equal((await request('/api/clients',{cookie:friendCookie})).status,401);
  assert.equal((await post('/api/auth/login',{email:'friend@example.com',password:'wrong-password'})).status,401);
  assert.equal((await post('/api/auth/login',{email:'friend@example.com',password:'another-long-password'})).status,200);
 }finally{
  globalThis.fetch=nativeFetch;if(closeStudio)await closeStudio();
  for(const [key,value] of Object.entries(previous)){const name={dir:'VT_AI_DATA_DIR',key:'OPENAI_API_KEY',setup:'VT_AI_SETUP_CODE',origin:'VT_AI_PUBLIC_ORIGIN'}[key];if(value===undefined)delete process.env[name];else process.env[name]=value}
  assert.equal(path.dirname(dir),path.resolve(os.tmpdir()));assert.ok(path.basename(dir).startsWith('vt-ai-http-'));fs.rmSync(dir,{recursive:true,force:true});
 }
});
